updated windows installation instructions
deepanshs/mrsimulator pull request #129
Opened 2022-03-15 16:27 UTC by mccarthy677

2022-03-19 17:28 UTC, deepanshs requested changes

2022-03-19 17:28 UTC, deepanshs commented on docs/installation/users.rst
> +    window, type
@mccarthy677 The installation step is same for all python versions (anaconda build or python.org build)--- `pip install mrsimulator`

For anaconda users, if the python version is 3.8-3.10, you will need to specify 
`$ set CONDA_DLL_SEARCH_MODIFICATION_ENABLE='1'` in the anaconda terminal before running mrsimulator script.

2022-03-21 23:44 UTC, deepanshs commented
@mccarthy677 That is not what I meant. I am adding @mgiammar to this PR.

Here's what we can do- since all os installation uses `pip install mrsimulator`, there is no need for os tabs. Get rid of the tabs and add any os specific info as notes. For example, in the case of windows, it will be something like,

Windows users using anaconda python 3.8 and up, set the environment variable in the Anaconda Prompt by typing, `set CONDA_DLL_SEARCH_MODIFICATION_ENABLE='1'`, before running mrsimulator scripts or a Jupiter notebook session.

2022-03-21 23:44 UTC, deepanshs commented
@mccarthy677 That is not what I meant. I am adding @mgiammar to this PR.

Here's what we can do- since all os installation uses `pip install mrsimulator`, there is no need for os tabs. Get rid of the tabs and add any os specific info as notes. For example, in the case of windows, it will be something like,

Windows users using anaconda python 3.8 and up, set the environment variable in the Anaconda Prompt by typing, `set CONDA_DLL_SEARCH_MODIFICATION_ENABLE='1'`, before running mrsimulator scripts or a Jupiter notebook session.

2022-03-26 23:01 UTC, mgiammar submitted a review, later dismissed

2022-03-27 17:25 UTC, deepanshs approved these changes

2022-03-27 17:35 UTC, mgiammar approved these changes

2022-03-27 18:11 UTC, merged