Implement capability for creating user-defined isotopes
deepanshs/mrsimulator pull request #226
Opened 2022-08-10 15:33 UTC by mgiammar

Closes #145 

- [x] Write custom isotope function
- [x] Test new code
- [x] Document new features (changelog & api)

2022-08-22 11:32 UTC, deepanshs commented on src/mrsimulator/spin_system/isotope.py
> +):
Can this be a classmethod of `Isotope` class? Something like, `Isotope.add_new()`!

2022-09-01 23:59 UTC, deepanshs requested changes

2022-09-01 23:59 UTC, deepanshs commented on src/mrsimulator/spin_system/isotope.py
> +            return Isotope(symbol=symbol)
If the symbol already exits in `custom_isotope_data`, it should raise an error. Consider two entries with same symbol but different spin. At present, the first entry will take priority. The better approach is to not allow duplicate symbols.

2022-09-01 23:59 UTC, deepanshs commented on src/mrsimulator/spin_system/isotope.py
> +            return Isotope(symbol=symbol)
Remove atomic number from the custom isotopes. While real isotopes share symbol but vary in atomic number, custom isotropic should be unique symbols.

Just return `0` from `def atomic_number` when attribute is no present.

2022-09-01 23:59 UTC, deepanshs commented on src/mrsimulator/spin_system/isotope.py
> +    def add_new(
How about the function name `def new()`?

2022-09-02 00:05 UTC, deepanshs commented
How about a utility function for the Isotope class that creates a copy of the in-build isotopes as a custom isotope but with a different symbol?

```py
Ha = Isotope.copy(symbol='Ha', from='1H')
```

I see this being a lot useful.

2022-09-03 00:48 UTC, deepanshs commented
> How about a utility function for the Isotope class that creates a copy of the in-build isotopes as a custom isotope but with a different symbol?
> 
> ```python
> Ha = Isotope.copy(symbol='Ha', from='1H')
> ```
> 
> I see this being a lot useful.

On second thought, 

```py
Ha = Isotope.new(symbol='Ha', copy_from='1H')
```
might be better. A single function `new` will generate a custom isotope, and if `copy_from` is provided, a custom isotope from the given `copy_from` isotope.

2022-09-03 00:57 UTC, mgiammar commented
> > How about a utility function for the Isotope class that creates a copy of the in-build isotopes as a custom isotope but with a different symbol?
> > ```python
> > Ha = Isotope.copy(symbol='Ha', from='1H')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I see this being a lot useful.
> 
> On second thought,
> 
> ```python
> Ha = Isotope.new(symbol='Ha', copy_from='1H')
> ```
> 
> might be better. A single function `new` will generate a custom isotope, and if `copy_from` is provided, a custom isotope from the given `copy_from` isotope.

I agree a function which copies an isotope but with a new symbol would be the most useful; this is easily implemented with a mapping where the new symbol points to the original symbol and the original symbol points to the `isotope_data.json` data. This way no new information needs to be stored and the mapping can be serialized with the `spin_systems` list.

As we discussed in meeting, I don't think non-real isotopes would be that useful

2022-09-05 16:48 UTC, deepanshs commented
Here are some errors I get when running code through this PR.

- In a notebook env, if I run this following code block once, it fine. 

```py
a = Isotope.new(symbol='H1a', copy_from='1H')
```

If I rerun, it gives the following error

```shell
mrsimulator/mrsimulator/src/mrsimulator/spin_system/isotope.py in new(cls, symbol, copy_from)
     77         """
     78         if symbol in ISOTOPE_DATA or symbol in custom_isotope_mapping:
---> 79             raise ValueError(
     80                 "The new symbol for the copied isotope cannot match any previous "
     81                 f"isotope symbols. Got {symbol} which matches a known symbol."

ValueError: The new symbol for the copied isotope cannot match any previous isotope symbols. Got H1a which matches a known symbol.
```

2022-09-05 16:52 UTC, deepanshs commented
- Running the simulation with custom isotope.

```py
a = Isotope.new(symbol='H1a', copy_from='1H')
sys = SpinSystem(sites=[Site(isotope='H1a')])
method = BlochDecaySpectrum(channels=['H1a'])
sim = Simulator(spin_systems=[sys], methods=[method])
sim.run()
```

gives a value error. The error log is long. It seems to originate from the parallel run.
 
```shell
ValueError: need more than 1 value to unpack
```

2022-09-05 16:55 UTC, deepanshs commented
- Reading spin systems from file without the `isotope_mappings` key,

```shell
File "/home/docs/checkouts/readthedocs.org/user_builds/mrsimulator/checkouts/226/examples_source/2D_simulation(crystalline)/plot_6_PASS_itraconazole_drug.py", line 30, in <module>
    sim.load_spin_systems(filename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mrsimulator/envs/226/lib/python3.8/site-packages/mrsimulator-0.8.0.dev0-py3.8-linux-x86_64.egg/mrsimulator/simulator/__init__.py", line 274, in load_spin_systems
    _ = [Isotope.new(k, v) for k, v in contents["isotope_mappings"].items()]
TypeError: list indices must be integers or slices, not str
```

2023-05-11 23:23 UTC, deepanshs commented on src/mrsimulator/spin_system/isotope.py
> +                "The copy_from symbol must match a known isotope, but "
maybe just have this message. 

```py
f"Unknown isotope symbol: {copy_from}"
```

2023-05-15 19:00 UTC, mgiammar commented
New features moved to #250

2023-05-15 19:00 UTC, closed without merging