Invalid class attributes raise ValidationError
deepanshs/mrsimulator pull request #90
Opened 2021-10-30 19:36 UTC by mgiammar

Unknown class attributes, such as misspelt ones, will now raise `ValidationError` when instantiating and object.

2021-11-06 16:07 UTC, mgiammar commented
The Simulator class does not have `extra="forbid"` for compatibility with external apps. Any extra tags are added as attributes to a simulator instance when calling `mrsimulator.load` and those tags are re-serialized when calling `mrsimulator.save`.

@deepanshs Is this acceptable since packing all extra keywords into a metadata tag could cause issues when other applications expect certain keywords to exist at the base level?

2021-11-06 21:30 UTC, deepanshs commented
> @deepanshs Is this acceptable since packing all extra keywords into a metadata tag could cause issues when other applications expect certain keywords to exist at the base level?

@mgiammar @pjgrandinetti What other applications are you referring to? We could use the same concept as used in CSDM. Add `application` keyword to the `Simulator` class, and applications can then serialize their metadata as a dictionary under this keyword with the reverse domain name as its unique key.

2021-11-07 20:12 UTC, deepanshs requested changes

2021-11-07 20:19 UTC, mgiammar commented on src/mrsimulator/__init__.py
>          else [SignalProcessor() for _ in sim.methods]
I changed this piece of code back to what was originally there. I think adding a super-class that holds `signal_processor` and `sim` should be separate from this one and the parse code would change in there.

2021-11-07 22:22 UTC, deepanshs approved these changes

2021-11-08 00:27 UTC, merged